#注意：如果在记事本上编写，下面的缩进不要使用Tab来缩进，不然报错
spring:
  profiles:
    active: dev # 激活开发环境配置
---
server:
  port: 8080
spring:
  profiles: dev # 开发环境
  application:
    name: microservice-product-config     # ******服务名*******
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.10.11:33306/springcloud_db01?serverTimezone=GMT%2B8 #数据库连接地址，
    username: root
    password: 123456
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 150

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://192.168.10.11:6001/eureka
  instance:
    instanceId: ${spring.application.name}:${server.port}
    prefer-ip-address: true 
---
server:
  port: 8080
spring:
  profiles: prod # 生产环境
  application:
    name: microservice-product-config     # ******服务名*******
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.10.11:33306/springcloud_db02?serverTimezone=GMT%2B8 #数据库连接地址，
    username: root
    password: 123456
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 150

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://192.168.10.11:6001/eureka
  instance:
    instanceId: ${spring.application.name}:${server.port}
    prefer-ip-address: true 
    
emp: 
  name: zhangsan
  password: '{cipher}AQDGJxF6MXoamaQm94qwt/mxtzMZRBuI6CK89ShOUJ8vq43sZK0KqiYW4vvv4GX2xjr00xlPEV5vLNxwwGIn8AGt9PDpBDzCk0tClDIRpSY8hd9xIMfxKn9j/pjsnOTPE9AIDkbedohbsoBkE7KKTAe0ARaKSDJoMdMCDl0SGs66JzP78+8zPdjx5lf5zeplwGFXFE9K9Mb/DJSsciF+zRPaY+udf+xT5nWluo6QukB2KqZUh7PFTjRJzDDkKug+bL/C+/+2Elv3pTrboqfzvW6bQcx92BpWWmgyXjhNCUHOcc2rm8uOQ2obhRFsfe++W1Rc0hHw902ar9RHfKGrFWC5OLwgI8Ya69dcKhA/Yf0zMsGutwhyf4nZixPYOic7/3E='